services:
  - type: web
    name: notes-versions
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: alembic upgrade head && gunicorn app.main:app -k uvicorn.workers.UvicornWorker
